import type { Metadata } from "next";
import "../globals.css";
import { AppSidebar } from "@/components/app-sidebar";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { SiteHeader } from "@/components/site-header";
import { ApolloProviderComponent } from "@/components/apollo-provider";
import { AuthContextProvider, User } from "@/components/context-provider";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fetchAuth = async () => {
  const cookieStore = await cookies();
  const cookieHeader = cookieStore.toString();

  const response = await fetch("http://localhost:5000/graphql", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Cookie: cookieHeader,
    },
    body: JSON.stringify({
      query: `
        query getAuthUser {
          getAuthUser {
            id
            email
            user_type
            employee {
              firstName
              lastName
              imgPath
            }
            company {
              name
              imgPath
            }
          }
        }
      `,
    }),
    cache: "no-store",
  });

  return response.json();
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const authUser = await fetchAuth();

  const user = authUser?.data?.getAuthUser as User;

  return (
    <AuthContextProvider user={user}>
      <SidebarProvider
        style={
          {
            "--sidebar-width": "calc(var(--spacing) * 72)",
            "--header-height": "calc(var(--spacing) * 12)",
          } as React.CSSProperties
        }
      >
        <AppSidebar variant="inset" />
        <SidebarInset>
          <SiteHeader />
          <div className="p-4">{children}</div>
        </SidebarInset>
      </SidebarProvider>
    </AuthContextProvider>
  );
}
